/**
 *
 * $Id$
 */
package org.eclipse.bpmn2.validation;

import java.util.List;

import org.eclipse.bpmn2.InputOutputBinding;
import org.eclipse.bpmn2.InputOutputSpecification;
import org.eclipse.bpmn2.Interface;

/**
 * A sample validator interface for {@link org.eclipse.bpmn2.CallableElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CallableElementValidator {
    boolean validate();

    boolean validateSupportedInterfaceRefs(List<Interface> value);

    boolean validateIoSpecification(InputOutputSpecification value);

    boolean validateIoBinding(List<InputOutputBinding> value);

    boolean validateName(String value);
}
