/**
 *
 * $Id$
 */
package org.eclipse.bpmn2.validation;

import java.util.List;

import org.eclipse.bpmn2.DataOutput;
import org.eclipse.bpmn2.DataOutputAssociation;
import org.eclipse.bpmn2.EventDefinition;
import org.eclipse.bpmn2.OutputSet;

/**
 * A sample validator interface for {@link org.eclipse.bpmn2.CatchEvent}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CatchEventValidator {
    boolean validate();

    boolean validateDataOutputs(List<DataOutput> value);

    boolean validateDataOutputAssociation(List<DataOutputAssociation> value);

    boolean validateOutputSet(OutputSet value);

    boolean validateEventDefinitions(List<EventDefinition> value);

    boolean validateEventDefinitionRefs(List<EventDefinition> value);

    boolean validateParallelMultiple(boolean value);
}
