/**
 *
 * $Id$
 */
package org.eclipse.bpmn2.validation;

import java.util.List;

import org.eclipse.bpmn2.InputSet;

/**
 * A sample validator interface for {@link org.eclipse.bpmn2.DataInput}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DataInputValidator {
    boolean validate();

    boolean validateInputSetWithOptional(List<InputSet> value);

    boolean validateInputSetWithWhileExecuting(List<InputSet> value);

    boolean validateInputSetRefs(List<InputSet> value);

    boolean validateIsCollection(boolean value);

    boolean validateName(String value);
}
