/**
 *
 * $Id$
 */
package org.eclipse.bpmn2.validation;

import java.util.List;

import org.eclipse.bpmn2.Assignment;
import org.eclipse.bpmn2.FormalExpression;
import org.eclipse.bpmn2.ItemAwareElement;

/**
 * A sample validator interface for {@link org.eclipse.bpmn2.DataAssociation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DataAssociationValidator {
    boolean validate();

    boolean validateSourceRef(List<ItemAwareElement> value);

    boolean validateTargetRef(ItemAwareElement value);

    boolean validateTransformation(FormalExpression value);

    boolean validateAssignment(List<Assignment> value);

    boolean validateName(String value);
}
