/**
 *
 * $Id$
 */
package org.eclipse.bpmn2.validation;

import java.util.List;

import org.eclipse.bpmn2.Rendering;

/**
 * A sample validator interface for {@link org.eclipse.bpmn2.GlobalUserTask}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface GlobalUserTaskValidator {
    boolean validate();

    boolean validateRenderings(List<Rendering> value);

    boolean validateImplementation(String value);
}
