/**
 *
 * $Id$
 */
package org.eclipse.bpmn2.validation;

import java.util.List;

import org.eclipse.bpmn2.DataInput;
import org.eclipse.bpmn2.DataOutput;
import org.eclipse.bpmn2.InputSet;
import org.eclipse.bpmn2.OutputSet;

/**
 * A sample validator interface for {@link org.eclipse.bpmn2.InputOutputSpecification}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface InputOutputSpecificationValidator {
    boolean validate();

    boolean validateDataInputs(List<DataInput> value);

    boolean validateDataOutputs(List<DataOutput> value);

    boolean validateInputSets(List<InputSet> value);

    boolean validateOutputSets(List<OutputSet> value);
}
