/**
 *
 * $Id$
 */
package org.eclipse.bpmn2.validation;

/**
 * A sample validator interface for {@link org.eclipse.bpmn2.VrSpecification}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface VrSpecificationValidator {
    boolean validate();

    boolean validateVarPoint(boolean value);

    boolean validateVarPointType(String value);

    boolean validateVariant(boolean value);

    boolean validateVariantType(String value);

    boolean validateVariabilityType(String value);

    boolean validateSequencial(String value);

    boolean validateFeatureId(String value);

}
