/**
 *
 * $Id$
 */
package org.eclipse.bpmn2.validation;

import java.util.List;
import org.eclipse.bpmn2.InputSet;
import org.eclipse.bpmn2.OutputSet;
import org.eclipse.bpmn2.VariabilitySpecification;

/**
 * A sample validator interface for {@link org.eclipse.bpmn2.DataObject}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DataObjectValidator {
    boolean validate();

    boolean validateIsCollection(boolean value);

    boolean validateOutputSetRefs(List<OutputSet> value);

    boolean validateInputSetRefs(List<InputSet> value);

    boolean validateVrSpecification(VariabilitySpecification value);

    boolean validateVarPoint(boolean value);

    boolean validateVarPointType(String value);

    boolean validateVariant(boolean value);

    boolean validateVariantType(String value);

    boolean validateVariabilityType(String value);

    boolean validateSequencial(String value);

    boolean validateFeatureId(String value);
}
