/**
 *
 * $Id$
 */
package org.eclipse.bpmn2.validation;

import java.util.List;

import org.eclipse.bpmn2.Extension;
import org.eclipse.bpmn2.Import;
import org.eclipse.bpmn2.Relationship;
import org.eclipse.bpmn2.RootElement;

import org.eclipse.bpmn2.di.BPMNDiagram;

/**
 * A sample validator interface for {@link org.eclipse.bpmn2.Definitions}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DefinitionsValidator {
    boolean validate();

    boolean validateImports(List<Import> value);

    boolean validateExtensions(List<Extension> value);

    boolean validateRootElements(List<RootElement> value);

    boolean validateDiagrams(List<BPMNDiagram> value);

    boolean validateRelationships(List<Relationship> value);

    boolean validateExporter(String value);

    boolean validateExporterVersion(String value);

    boolean validateExpressionLanguage(String value);

    boolean validateName(String value);

    boolean validateTargetNamespace(String value);

    boolean validateTypeLanguage(String value);
}
