/**
 *
 * $Id$
 */
package org.eclipse.bpmn2.validation;

import java.util.List;

import org.eclipse.bpmn2.EndPoint;
import org.eclipse.bpmn2.Interface;
import org.eclipse.bpmn2.ParticipantMultiplicity;

/**
 * A sample validator interface for {@link org.eclipse.bpmn2.Participant}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ParticipantValidator {
    boolean validate();

    boolean validateInterfaceRefs(List<Interface> value);

    boolean validateEndPointRefs(List<EndPoint> value);

    boolean validateParticipantMultiplicity(ParticipantMultiplicity value);

    boolean validateName(String value);

    boolean validateProcessRef(org.eclipse.bpmn2.Process value);
}
