/**
 *
 * $Id$
 */
package org.eclipse.bpmn2.di.validation;

import java.util.List;

import org.eclipse.bpmn2.di.BPMNLabelStyle;
import org.eclipse.bpmn2.di.BPMNPlane;

/**
 * A sample validator interface for {@link org.eclipse.bpmn2.di.BPMNDiagram}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BPMNDiagramValidator {
    boolean validate();

    boolean validatePlane(BPMNPlane value);

    boolean validateLabelStyle(List<BPMNLabelStyle> value);
}
