/**
 *
 * $Id$
 */
package org.eclipse.bpmn2.di.validation;

import org.eclipse.bpmn2.BaseElement;

import org.eclipse.bpmn2.di.BPMNLabel;
import org.eclipse.bpmn2.di.MessageVisibleKind;

import org.eclipse.dd.di.DiagramElement;

/**
 * A sample validator interface for {@link org.eclipse.bpmn2.di.BPMNEdge}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BPMNEdgeValidator {
    boolean validate();

    boolean validateLabel(BPMNLabel value);

    boolean validateBpmnElement(BaseElement value);

    boolean validateMessageVisibleKind(MessageVisibleKind value);

    boolean validateSourceElement(DiagramElement value);

    boolean validateTargetElement(DiagramElement value);
}
