/**
 *
 * $Id$
 */
package org.eclipse.dd.di.validation;

import java.util.List;

import org.eclipse.dd.di.Diagram;
import org.eclipse.dd.di.DiagramElement;
import org.eclipse.dd.di.Style;

/**
 * A sample validator interface for {@link org.eclipse.dd.di.DiagramElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DiagramElementValidator {
    boolean validate();

    boolean validateOwningDiagram(Diagram value);

    boolean validateOwningElement(DiagramElement value);

    boolean validateOwnedElement(List<DiagramElement> value);

    boolean validateModelElement(Object value);

    boolean validateStyle(Style value);

    boolean validateId(String value);
}
