/**
 *
 * $Id$
 */
package org.eclipse.dd.di.validation;

import java.util.List;

import org.eclipse.dd.di.DiagramElement;
import org.eclipse.dd.di.Style;

/**
 * A sample validator interface for {@link org.eclipse.dd.di.Diagram}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DiagramValidator {
    boolean validate();

    boolean validateDocumentation(String value);

    boolean validateOwnedStyle(List<Style> value);

    boolean validateRootElement(DiagramElement value);

    boolean validateId(String value);

    boolean validateName(String value);

    boolean validateResolution(float value);
}
