/**
 *
 * $Id$
 */
package org.eclipse.dd.dc.validation;

import java.util.Map;

import org.eclipse.dd.dc.Bounds;
import org.eclipse.dd.dc.Font;
import org.eclipse.dd.dc.Point;

import org.eclipse.emf.ecore.util.FeatureMap;

/**
 * A sample validator interface for {@link org.eclipse.dd.dc.DocumentRoot}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DocumentRootValidator {
    boolean validate();

    boolean validateMixed(FeatureMap value);

    boolean validateXMLNSPrefixMap(Map<String, String> value);

    boolean validateXSISchemaLocation(Map<String, String> value);

    boolean validateBounds(Bounds value);

    boolean validateFont(Font value);

    boolean validatePoint(Point value);
}
